name: brain_up
description: BrainUp mobile app for short daily logic and thinking challenges.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flame: ^1.37.0
  flame_audio: ^2.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: any
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/generated/
    - assets/images/puzzles/
    - assets/images/characters/
    - assets/images/worlds/
    - assets/images/rewards/
    - assets/images/effects/
